### ISSUE TITLE
Fix user level calculation

### ISSUE THREAD

**Issue by aabeling** [viadee/sonarQuest#115] opened 2018-07-06 11:22 UTC
The GratificationService calculates the new user level with the LevelService which is based on levels defined in the database.
The UserService is using the LevelService for calculation of the initial level one the one hand 
and the method calculateLevel in getLevel for the ArtefactService on the other hand.

For sake of simplicity I would prefer the simple fixed calculation of the level (like in calculateLevel) instead of the more flexible definition of levels in the database.

**Comment by bm-viadee** [comment] 2018-07-13 20:15
Root cause of the issues was the creation of new levels whenever the user was gratified and no level was defined for the amount of XP. As only levels 0 and 1 were defined in the standard game data - every gratification led to a new level.

Levels 1 to 100 including the correct XP-values are now included in the standard game data. Added new column "level" for the level table in order to fix the issue of muddling the technical id of the level with its stage/name. Levels are no longer dynamically created within the application, they have to be added in the database according to the calculöation documentation (added in /docs).
Furthermore, the current level of the user is now calculated only at LevelService (getLevelByUserXp).

branch: level-refactoring (not merged to master yet)

**Comment by Christoph-Meyer** [comment] 2018-07-16 16:40
Branch was merged.

**Comment by Christoph-Meyer** [comment] 2018-07-16 16:41
Issue fixed, closed.

**Closed by Christoph-Meyer** 2018-07-16 16:41 UTC
Labels: bug, priority
